### ISSUE TITLE
Ubuntu 18.04

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cp2019#15]
# 安裝 fcitx 中文輸入
## step 1
sudo apt install fcitx fcitx-chewing
## step 2
sudo mv /usr/bin/ibus-daemon /usr/bin/ibus-daemon.bak
sudo reboot
## step 3
右上方以滑鼠點選 input method 中的 Configure 進入 Input Method Configuration 視窗設定畫面.
畫面將只呈現 Keybord - English (US)
必須增加 Chewing input method, 方法為點選左下方的 + 號, 去除 Only Show Current Language 選項, 然後用搜尋, 輸入 Chewing 表示要將注音輸入法納入 Input Method 中.

完成上述三項步驟後, 就可以利用 Ctrl + Space 或鍵盤左側的 Shift 鍵切換中英輸入, 選擇同音字時則利用方向鍵與數字鍵進行選字.

**Comment by mdecourse** [comment]
# vmdk to vdi

在 Ubuntu 建立虛擬主機時, 無法使用 vmdk 格式, 嘗試將 vmdk 轉換為 vdi 格式.

VBoxManage clonemedium --format VDI win10_64.vmdk win10_64.vdi

**Comment by 40823225** [comment]
.

**Comment by 40823225** [comment]
.

**Comment by 40823225** [comment]
.
