### ISSUE TITLE
W9 期中考週任務規劃

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cp2019#16]
# 各學員製作帶字幕期中報告影片
影片必須加上期中考時段所宣布的內容浮水印後, 上傳至 Youtube 嵌入個人網誌後回報至特定位置
# 利用 Ethercalc 取各學員自評成績

https://ethercalc.net/

在 Ubuntu 18.04 操作系統中安裝 Ethercalc, 並令其開機時啟動.

安裝 node.js 6.x 版

curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

sudo apt-get install -y nodejs

安裝 redis server

sudo apt install redis-server

安裝 ethercalc

sudo npm i -g ethercalc

編輯 /etc/rc.local

加入 ethercalc 啟動指令

重新開機後, 就可以利用 http://your ip or domain name:8000 連接 Ethercalc 網頁

# 以 Dartpad 數值分析法解

http://mde.tw/cp2019/downloads/dart_ex/runge_kutta/Ordinary%20differential%20equation%20examples.pdf

三個題目, 完成後拍攝過程影片加上說明字幕上傳 Youtube 後, 包含執行心得放入個人網誌.

**Comment by 40823110** [comment]
老師dart 有數學次方的語法嗎?
