### ISSUE TITLE
cp2019 1a 期中報告任務回報

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cp2019#17]
# 各學員製作帶字幕期中報告影片
影片必須加上期中考時段所宣布的內容浮水印後, 上傳至 Youtube 嵌入個人網誌後回報至下列回應.

例如:

https://mdecourse.github.io/cp2019/blog/2019-Fall-Win10-1903.html

**Comment by 40823147** [comment]
https://youtu.be/l9_TKU_nbbA

**Comment by 40623155** [comment]
youtube.com/watch?v=Be3FjhY85_8

**Comment by 40623156** [comment]
https://youtu.be/6SGzit49lrc

**Comment by 40623153** [comment]
[https://youtu.be/HxAihL7LnhU](url)

**Comment by 40623157** [comment]
https://www.youtube.com/watch?v=uKdSx68UpYk

**Comment by 40823131** [comment]
https://40823131.github.io/cp2019/content/8th%20week.html

**Comment by 40823109** [comment]
https://40823109.github.io/cp2019/blog/index.html

**Comment by 40823127** [comment]
https://40823127.github.io/cp2019/content/%E6%9C%9F%E4%B8%AD%E5%BD%B1%E7%89%87%E7%B6%B2%E7%AB%99.html

**Comment by 40823142** [comment]
https://40823142.github.io/cp2019/content/index.html

**Comment by 40823131** [comment]
https://40823131.github.io/cp2019/blog/2019-Fall-midterm.html

**Comment by a40823112** [comment]
https://a40823112.github.io/cp2019/blog/2018-Fall-32-bit-Windows.html

**Comment by 40823120** [comment]
https://40823120.github.io/cp2019/blog/2019-Fall-Win10-1903.html

**Comment by 40823125** [comment]
https://40823125.github.io/cp2019/blog/2019-Fall-miderm.html

**Comment by 40823138** [comment]
https://40823138.github.io/cp2019/blog/123.html

**Comment by 40823137** [comment]
https://40823137.github.io/cp2019/blog/blog.html

**Comment by 40823151** [comment]
https://40823151.github.io/cp2019/blog/2019-Fall-Win10-1903.html

**Comment by 40823108** [comment]
https://40823108.github.io/cp2019/blog/2018-Fall-32-bit-Windows.html

**Comment by 40823127** [comment]
https://40823127.github.io/cp2019/blog/2019-Fall-youtube.html

**Comment by 40823113** [comment]
https://40823113.github.io/cp2019/blog/2018-Fall-32-bit-Windows.html

**Comment by 40823122** [comment]
https://40823122.github.io/cp2019/blog/2019-fall-32-bit-Windows.html

**Comment by 40823105** [comment]
https://40823105.github.io/cp2019/content/index.html

**Comment by 40823102** [comment]
https://40823102.github.io/cp2019/content/%E6%9C%9F%E4%B8%AD.html

**Comment by 40823106** [comment]
https://40823106.github.io/cp2019/content/%E6%9C%9F%E4%B8%AD.html

**Comment by 40823117** [comment]
https://40823117.github.io/cp2019/blog/2019-Fall-32-bit-Windows.html

**Comment by 40823111** [comment]
https://40823111.github.io/cp2019/blog/2018-Fall-32-bit-Windows.html

**Comment by 40823130** [comment]
https://40823130.github.io/cp2019/blog/index.html

**Comment by 40823144** [comment]
https://40823144.github.io/cp2019/blog/index.html

**Comment by 40823110** [comment]
https://40823110.github.io/cp2019/blog/2019-Fall-miderm.html

**Comment by 40823115** [comment]
https://40823115.github.io/cp2019/blog/2019-Fall-32-bit-Windows.html

**Comment by 40823107** [comment]
https://40823107.github.io/cp2019/blog/2019-Fall-Win10-1903.html#disqus_thread

**Comment by 40823145** [comment]
https://40823145.github.io/cp2019/blog/2019-Fall-32-bit-Windows.html

**Comment by 40823103** [comment]
https://40823103.github.io/cp2019/blog/2019-Fall-Win10-1903.html

**Comment by 40823141** [comment]
https://40823141.github.io/cp2019/blog/2019-Fall-Win10-qqq.html

**Comment by 40823146** [comment]
https://40823146.github.io/cp2019/blog/index.html

**Comment by 40823119** [comment]
https://40823119.github.io/cp2019/blog/2019-Fall-Win10-1903.html

**Comment by 40823146** [comment]
https://40823146.github.io/cp2019/blog/index.html

**Comment by 40823149** [comment]
https://40823149.github.io/cp2019/blog/2018-Fall-32-bit-Windows.html

**Comment by 40823135** [comment]
https://40823135.github.io/cp2019/blog/2019-Fall-Win10-1903.html

**Comment by 40823246** [comment]
https://40823246.github.io/cp2019/blog/video-test.html

**Comment by 40823143** [comment]
https://40823143.github.io/cp2019/blog/index.html

**Comment by 40823123** [comment]
https://40823123.github.io/cp2019/blog/2019-Fall-midterm.html

**Comment by 40823140** [comment]
https://40823140.github.io/cp2019/blog/2019-Fall-Win10-1.html

**Comment by 40823128** [comment]
https://40823128.github.io/cp2019/blog/2019-Fall-midterm.html

**Comment by 40823143** [comment]
https://40823147.github.io/cp2019/blog/youtub-report.html

**Comment by 40823147** [comment]
https://40823147.github.io/cp2019/blog/index.html

**Comment by 40823136** [comment]
https://40823136.github.io/cp2019/blog/2019-Fall-midterm.html

**Comment by 40823132** [comment]
https://40823132.github.io/c2019/blog/2019-Fall-Win10-1903.html

**Comment by 40823104** [comment]
https://40823104.github.io/cp2019/content/W8.html

**Comment by 40823126** [comment]
https://40823126.github.io/cp2019/blog/2019-Fall.html

**Comment by 40823150** [comment]
https://www.youtube.com/watch?v=IGZtNrY3OPE

**Comment by 40823129** [comment]
https://40823129.github.io/cp2019/blog/2019-Fall-midterm.html

**Comment by 40823114** [comment]
https://40823114.github.io/cp2019/blog/index.html

**Comment by s40523147** [comment]
https://s40523147.github.io/cp2019/blog/index.html

**Comment by 40823101** [comment]
https://40823101.github.io/cp2019/blog/2019-fall-Win-10-1903.html
