### ISSUE TITLE
cp2019 1b 期中報告任務回報

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cp2019#19]
# 各學員製作帶字幕期中報告影片
影片必須加上期中考時段所宣布的內容浮水印後, 上傳至 Youtube 嵌入個人網誌後回報至下列回應.

例如:

https://mdecourse.github.io/cp2019/blog/2019-Fall-Win10-1903.html

**Comment by 40823251** [comment]
https://40823251.github.io/cp2019/blog/40823251_w9.html

**Comment by s40523124** [comment]
https://s40523124.github.io/cp2019/blog/midtest.html

**Comment by s40523113** [comment]
https://s40523113.github.io/cp2019/blog/embed%20video.html

**Comment by 40823245** [comment]
[https://40823245.github.io/cp2019/blog/Midterm%20operation.html](url)

**Comment by 40823245** [comment]
[https://40823245.github.io/cp2019/blog/Midterm%20operation.html](url)

**Comment by 40823208** [comment]
https://40823208.github.io/cp2019/blog/video-1.html

**Comment by 40823223** [comment]
https://40823223.github.io/cp2019/blog/40823223-1.html

**Comment by 40823238** [comment]
https://40823238.github.io/cp2019/blog/2019-Fall-Windows10-1903-2.html

**Comment by 40823220** [comment]
https://40823220.github.io/cp2019/blog/%E6%9C%9F%E4%B8%AD%E8%80%83.html

**Comment by 40823239** [comment]
[https://40823239.github.io/cp2019/blog/2018-Fall-32-bit-Windows12142.html](url)

**Comment by 40823239** [comment]
https://40823239.github.io/cp2019/blog/2018-Fall-32-bit-Windows12142.html

**Comment by s40523242** [comment]
[https://s40523242.github.io/cp2019/blog/%E6%9C%9F%E4%B8%AD%E5%A0%B1%E5%91%8A%E5%BD%B1%E7%89%87.html](https://s40523242.github.io/cp2019/blog/%E6%9C%9F%E4%B8%AD%E5%A0%B1%E5%91%8A%E5%BD%B1%E7%89%87.html)

**Comment by s40523241** [comment]
[https://s40523241.github.io/cp2019/blog/2019-Fall-Win10-1107.html](https://s40523241.github.io/cp2019/blog/2019-Fall-Win10-1107.html)

**Comment by 40823235** [comment]
[https://40823235.github.io/cp2019/content/index.html](url)

**Comment by 40823247** [comment]
https://40823247.github.io/cp2019/blog/Durning-the-semester.html

**Comment by 40823235** [comment]
[](https://40823235.github.io/cp2019/content/index.html)

**Comment by 40823235** [comment]
[https://40823235.github.io/cp2019/content/index.html](url)

**Comment by 40823235** [comment]
https://40823235.github.io/cp2019/content/index.html

**Comment by 40823244** [comment]
https://40823244.github.io/cp2019/blog/40823244.html

**Comment by 40823213** [comment]
https://40823213.github.io/cp2019/blog/2019-Fall-Win10-1903.html

**Comment by 40823201** [comment]
https://40823201.github.io/cp2019/blog/midterm.html

**Comment by 40823212** [comment]
https://40823212.github.io/cp2019/blog/mid%20exam.html

**Comment by 40823234** [comment]
https://40823234.github.io/cp2019/blog/2019-Fall-Win10-1107.html

**Comment by 40823224** [comment]
https://40823224.github.io/cp2019/blog/40823224-1336.html

**Comment by 40823248** [comment]
https://40823248.github.io/cp2019/blog/vedio-test.html

**Comment by 40823226** [comment]
https://youtu.be/9HnjlVn2iO8

**Comment by 40823242** [comment]
https://40823242.github.io/cp2019/blog/40823242-1336.html

**Comment by 40823246** [comment]
https://40823246.github.io/cp2019/blog/video-test.html

**Comment by 40823210** [comment]
https://40823210.github.io/cp2019/blog/bang.html

**Comment by 40823235** [comment]
https://40823217.github.io/cp2019/blog/%E6%9C%9F%E4%B8%AD%E5%BD%B1%E7%89%87.html

**Comment by 40823217** [comment]
https://40823217.github.io/cp2019/blog/%E6%9C%9F%E4%B8%AD%E5%BD%B1%E7%89%87.html

**Comment by 40823211** [comment]
https://40823211.github.io/cp2019/blog/ji-gai-zuo-ye.html

**Comment by 40823233** [comment]
[https://40823233.github.io/cp2019/blog/40823233~~.html](url)

**Comment by 40823237** [comment]
https://youtu.be/E5GaYRK97TY

**Comment by 40823206** [comment]
https://www.youtube.com/watch?v=wmd-Fghm3mk&feature=youtu.be
(目前網頁出錯，搶救中，先上傳影片)

**Comment by s40523207** [comment]
https://s40523207.github.io/cp2019/content/w9%20%E6%9C%9F%E4%B8%AD%E5%BD%B1%E7%89%87.html

**Comment by 40823232** [comment]
https://www.youtube.com/watch?v=R_oC9a5aCq0&feature=youtu.be

**Comment by 40823250** [comment]
https://40823250.github.io/cp2019/blog/yu-vedio.html

**Comment by 40823225** [comment]
https://40823225.github.io/cp2019/blog/index.html

**Comment by 40823150** [comment]
<iframe width="560" height="315" src="https://www.youtube.com/embed/IGZtNrY3OPE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by 40823231-2** [comment]
https://youtu.be/JiSvq3sz__c

**Comment by 40823203** [comment]
https://40823203.github.io/cp2019/blog/index.html

**Comment by 40823231-2** [comment]
https://40823231-2.github.io/cp2019/blog/vedio.html

**Comment by 40823231-2** [comment]
https://40823231-2.github.io/cp2019/blog/vedio.html

**Comment by 40823221** [comment]
https://www.youtube.com/watch?v=4AfjxMv242A&feature=youtu.be

**Comment by 40823218** [comment]
https://40823218.github.io/cp2019/blog/20191108.html

**Comment by 40823205** [comment]
https://youtu.be/1LrJjFsCyjI

**Comment by 40823209** [comment]
[https://40823209.github.io/cp2019/content/index.html](url)

**Comment by 40823204** [comment]
https://40823204.github.io/cp2019

**Comment by 40823202** [comment]
https://40823202.github.io/cp2019/blog/40823202-1336.html

**Comment by 40823239** [comment]
https://www.youtube.com/watch?v=7uCHbMw3Fkc&feature=youtu.be

**Comment by 40823228** [comment]
https://www.youtube.com/watch?v=7uCHbMw3Fkc&feature=youtu.be
