### ISSUE TITLE
計算機程式課程 Q and A

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cp2019#4]
與計算機程式課程有關的問題, 請在此提出.

**Comment by a40823112** [comment]
老師我是設計一甲12號
我的倉儲名稱是a40823112

**Comment by s40732331** [comment]
午安
我是設計二乙的學生
學號是40732331

**Comment by 40823145** [comment]
9/26設計一甲上課影片還沒上傳?

**Comment by mdecourse** [comment]
Q:
宿舍網路只有ipv4,會跟學校的有衝突嗎?

A:
不會, 只要根據所處的網路環境進行對應設定即可.
通常在宿舍 (IPv4),  因為非系上網路區段, 因此必須將 .gitconfig 中的 http.proxy 以及瀏覽器的代理主機設定取消.

**Comment by mdecourse** [comment]
Q:
用自己電腦輸入python wsgi.py和安裝 flask_cors指令都沒有反應 在學校電腦卻可以 想請問老師這要怎麼解決

A:
1. 在 Windows 10 1903 的最新版本, 在命令列中輸入 python 時, 會自動檢查系統是否安裝 Python, 若系統並無安裝 Python, 則會跳出安裝 Python 的視窗.

這是因為我們使用可攜的 Python 造成的, 可以將 start.bat 中有關 path=%path%;.... 設定, 去除 %path%; 之後, 再重新啟動, 應該就可以正常使用可攜系統中的 Python.

2. 若仍不行, 假如在自己所有的電腦或者筆電, 可以考慮將 Python 與 git 安裝在系統中使用.

**Comment by s40523147** [comment]
Q：
老師我學校的電腦git clone 後跑出fatal: unable to access 'https://github.com/40823115/cp2019.git/': Could not resolve host: github.com，但在自己的電腦clone卻ok，想請問老師這怎麼解決??

**Comment by 40823231-2** [comment]
老師我的倉儲名稱是40823231-2
網站為https://40823231-2.github.io/cp2019/content/index.html

**Comment by 40823105** [comment]
Ｑ：插入圖片按下Save之後網頁跳成顯示IndexError: list index out of range且網頁使用各種方法皆無法打開，想請問如何處理？（Mac book使用者）

**Comment by s40523147** [comment]
Q：老師我有執行http-server檔了，進網頁9443改成8444然後網路就跳ERRO了，想請問怎麼處理

**Comment by 40823124** [comment]
老師請問dart語法中的'次方'該怎麼打呢?

**Comment by 40823201** [comment]
請問沒辦法執行ffmpeg，我該怎麼做 
![螢幕擷取畫面 (14)](https://user-images.githubusercontent.com/55229855/68393724-8f167000-01a7-11ea-9998-c7f93c597c41.png)

**Comment by 40823101** [comment]
老師請問如果我是使用手機分享wifi的話，那我的埠號該怎麼找尋呢?
![2019-11-08_01-00-23](https://user-images.githubusercontent.com/55519564/68410228-5e443400-01c3-11ea-9a80-a2e9215f6692.png)

**Comment by 40823209** [comment]
老師您好!!
我是機設一乙的同學
我的期中報告-影片已經做好了，但是系統已關閉，想請問老師，還能補交嗎？
[https://40823209.github.io/cp2019/blog/%E6%9C%9F%E4%B8%AD%E8%80%83.html](url)

**Comment by 40823251** [comment]
![未命名](https://user-images.githubusercontent.com/55229888/68845476-70176100-0706-11ea-97de-0a0119db1c78.png)
請問我在PUSH出現這個我該怎麼解決

**Comment by 40823110** [comment]
老師我遇到這個問題要怎麼解決
![wish_2019-11-14_22-25-17](https://user-images.githubusercontent.com/55223955/68866288-23944b80-072f-11ea-89c3-8a54c1c408ac.png)

**Comment by 40823246** [comment]
![111](https://user-images.githubusercontent.com/55502085/68867160-57bc3c00-0730-11ea-9808-d5ced5d2149f.png)
老師請問如何解決

**Comment by 40823110** [comment]
老師我遇到這個問題要怎麼解決
![wish_YUPMHjRa09](https://user-images.githubusercontent.com/55223955/68942891-a1fef500-07e4-11ea-9812-4f0e80eb19eb.png)

**Comment by 40823142** [comment]
老師為甚麼要pull的時候 會出現這個 _是金鑰的問題嗎？
![擷取](https://user-images.githubusercontent.com/55519002/68945394-47b56280-07eb-11ea-9e86-9ebe0ed2f177.PNG)

**Comment by 40823110** [comment]
老師我遇到這個問題要怎麼解決
wish_YUPMHjRa09

A:
將資料推送到 Github 倉儲的權限出問題, 檢查看看是不是 mdecourse/cad2019#20 中 Step 5 沒有指定 putty 格式的 private key.

我有用putty格式的private key但還是一樣的問題

**Comment by 40823110** [comment]
老師我遇到這個問題要怎麼解決
![68942891-a1fef500-07e4-11ea-9812-4f0e80eb19eb](https://user-images.githubusercontent.com/55223955/69003100-3f6a3e00-0937-11ea-86ca-0a167b8e911a.png)


A:
將資料推送到 Github 倉儲的權限出問題, 檢查看看是不是 mdecourse/cad2019#20 中 Step 5 沒有指定 putty 格式的 private key.

我有用putty格式的private key但還是一樣的問題

**Comment by 40823110** [comment]
老師請問是什麼問題無法開啟動態網頁?
![vOvdbAQT3A](https://user-images.githubusercontent.com/55223955/69051378-18972f00-0a3f-11ea-8bd3-4619fd79d9de.png)

**Comment by 40823251** [comment]
![未命名](https://user-images.githubusercontent.com/55229888/69347133-edb31200-0cae-11ea-8a14-2a4901e27c8c.png)
老師請問我解壓縮檔案遇到這是什麼問題?

**Comment by 40823246** [comment]
![68867160-57bc3c00-0730-11ea-9808-d5ced5d2149f](https://user-images.githubusercontent.com/55502085/69603701-6111a680-1056-11ea-9b99-63a561ee3084.png)
老師我git pull了,但還是出現這個,該如何解決?

**Comment by 40623157** [comment]
老師我在使用python開近端時，flaskapp.py出現錯誤請問要如何解決 
![cmd_2019-11-28_09-37-52](https://user-images.githubusercontent.com/43258777/69770413-ea92b700-11c3-11ea-9b22-1241942189d9.png)
![SciTE_2019-11-28_09-38-21](https://user-images.githubusercontent.com/43258777/69770423-f4b4b580-11c3-11ea-9ab3-e1928a544a8b.png)

**Comment by 40823144** [comment]
![image](https://user-images.githubusercontent.com/55223830/69771943-82df6a80-11c9-11ea-835f-3789775245d7.png)
老師這是我python cmsimde進入9443後出現的問題，想請問如何解決

**Comment by 40823219** [comment]
![擷取](https://user-images.githubusercontent.com/55229934/69805852-8f40e300-121c-11ea-89df-ddef3daf591e.PNG)

老師請問PUSH時遇到fatal: not a git repository: cmsimde/../.git/modules/cmsimde 是甚麼問題

**Comment by 40823219** [comment]
> Q:
> ![擷取](https://user-images.githubusercontent.com/55229934/69805852-8f40e300-121c-11ea-89df-ddef3daf591e.PNG)
> 
> 老師請問PUSH時遇到fatal: not a git repository: cmsimde/../.git/modules/cmsimde 是甚麼問題
> 
> A:
> 在 .git 中所登錄的子模組 cmsimde 與目前 cmsimde 子目錄中的內容不符, 可能是重建子模組或刪除先前子模組的過程發生錯誤.

老師請問要如何解決

**Comment by s40523147** [comment]
Q：
![1575309825240](https://user-images.githubusercontent.com/22387400/69983386-8aa86180-1571-11ea-8478-371ea1a0aef7.jpg)
老師我不小心把之前設好的金鑰刪掉了，我再用id_rsa.pub再新增一次的時候，就跳出那行字了。跪求老師相救!!

**Comment by 40823110** [comment]
![2019-12-08_17-19-19](https://user-images.githubusercontent.com/55223955/70387340-3ffa6f80-19df-11ea-8c59-bb791de7b12d.png)
老師我無法打開9443網頁請問是甚麼問題?

**Comment by 40823110** [comment]
老師輸入python wsgi.py 顯示 no module named 'stat'之後我輸入python -m pip install stat還是一樣錯誤要如何解決
![cmd_drvFMYGWsC](https://user-images.githubusercontent.com/55223955/70433838-a5249280-1abd-11ea-998b-0361e84283bd.png)

**Comment by 40823110** [comment]
老師我測試之後確定是隨身碟的問題要怎麼解決?

**Comment by 40823251** [comment]
![未命名](https://user-images.githubusercontent.com/55229888/70722173-c4c3f100-1d31-11ea-979c-54fc67564a6c.png)
老師請問偵測不到我的home，一直出現錯誤我該如何解決。

**Comment by 40823110** [comment]
老師我啟動9443時出現這個是什麼問題
![1](https://user-images.githubusercontent.com/55223955/70761371-f1a2f300-1d87-11ea-820b-98a1fa369166.png)
![2](https://user-images.githubusercontent.com/55223955/70761373-f36cb680-1d87-11ea-9ba5-ab3f898befa7.png)
![3 (2)](https://user-images.githubusercontent.com/55223955/70761379-f667a700-1d87-11ea-9f6c-51f7668e54ce.png)

**Comment by 40823110** [comment]
Q:
老師我啟動9443時出現這個是什麼問題
1
2
3 (2)
A:
你是在 32 位元的操作系統上工作嗎? 課堂上的可攜系統只能用在 Windows 64 位元系統中執行.
A:老師我的電腦是window7 64位元的操作系統

**Comment by 40823110** [comment]
A:
老師我的電腦是window7 64位元的操作系統

**Comment by 40823110** [comment]
A:
老師我的電腦是window7 64位元的操作系統
但我用其他同學window10 的電腦就沒有問題是window7的問題嗎?

**Comment by mdecourse** [comment]
# How do I unlink Windows 10 from my microsoft account?

https://answers.microsoft.com/en-us/windows/forum/all/how-do-i-unlink-windows-10-from-my-microsoft/d287425e-8a22-48f7-987b-49403e754d09

**Comment by 40823225** [comment]
老師我做完之後要推上去一直長這樣之後不管案y或n也都沒反應

> 
![計概](https://user-images.githubusercontent.com/55229945/71781529-cd46d900-300a-11ea-868b-851e13e5d43d.jpg)
![計概2](https://user-images.githubusercontent.com/55229945/71781530-ce780600-300a-11ea-8608-a1e0682860f7.jpg)
