### ISSUE TITLE
1a W6 Dart for 迴圈程式原始碼與 Gist 連結放入網頁回報

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cp2019#8]
請參考 https://www.youtube.com/watch?v=HyBa_29aflg 中有關 main 主函式與 for 迴圈使用說明, 將第一個 for 迴圈應用程式原始碼引入個人頁面連結與 Gist  連結, 在下列回應中回報.

例如:

[課程網頁中的亂數分組](http://mde.tw/cp2019/content/Dart2%20%E5%9F%BA%E6%9C%AC%E8%AA%9E%E6%B3%95.html)

請提供個人網頁中 w6 的頁面網路連結

**Comment by 40823125** [comment]
https://40823125.github.io/cp2019/

**Comment by 40823131** [comment]
https://40823131.github.io/cp2019/content/%E4%BA%82%E6%95%B8%E5%88%86%E7%B5%84%E7%A8%8B%E5%BC%8F.html

**Comment by 40823131** [comment]
https://40823131.github.io/cp2019/content/%E8%BF%B4%E5%9C%88%E7%A8%8B%E5%BC%8F.html

**Comment by 40823127** [comment]
https://40823127.github.io/cp2019/content/About.html

**Comment by 40823117** [comment]
https://40823117.github.io/cp2019/content/Dartpad.html

**Comment by 40823142** [comment]
https://40823142.github.io/cp2019/content/%E4%BA%82%E6%95%B8%E5%88%86%E7%B5%84%E7%A8%8B%E5%BC%8F.html

**Comment by 40823151** [comment]
https://40823151.github.io/cp2019/content/index.html 
I'm so happy!!!

**Comment by 40823109** [comment]
https://40823109.github.io/cp2019/content/index.html

**Comment by a40823112** [comment]
https://a40823112.github.io/cp2019/content/index.html

**Comment by 40823122** [comment]
https://40823122.github.io/cp2019/content/dart.html

**Comment by 40823113** [comment]
https://40823113.github.io/cp2019/content/index.html

**Comment by 40823108** [comment]
https://40823108.github.io/cp2019/content/index.html

**Comment by 40823111** [comment]
https://40823111.github.io/cp2019/content/index.html

**Comment by 40823145** [comment]
https://40823145.github.io/cp2019/content/index.html

**Comment by 40823128** [comment]
https://40823128.github.io/cp2019/content/index.html

**Comment by 40823123** [comment]
https://40823123.github.io/cp2019/content/%E8%BF%B4%E5%9C%88%E7%A8%8B%E5%BC%8F.html

**Comment by 40823129** [comment]
https://40823129.github.io/cp2019/content/index.html

**Comment by 40823110** [comment]
https://40823110.github.io/cp2019/content/loop.html

**Comment by 40823144** [comment]
https://40823144.github.io/cp2019/content/About.html

**Comment by 40823115** [comment]
https://40823115.github.io/cp2019/content/index.html

**Comment by 40823102** [comment]
https://40823102.github.io/cp2019/content/index.html

**Comment by 40823106** [comment]
https://40823106.github.io/cp2019/content/index.html

**Comment by 40823115** [comment]
https://40823115.github.io/cp2019/content/index.html

**Comment by 40823121** [comment]
https://40823121.github.io/cp2019/content/%E8%BF%B4%E5%9C%88%E7%A8%8B%E5%BC%8F.html

**Comment by 40823130** [comment]
https://40823130.github.io/cp2019/content/index.html

**Comment by 40823148** [comment]
https://40823148.github.io/cp2019/content/%E4%B8%BB%E5%A7%94%E4%BE%86%E5%8A%A0%E7%A2%BC.html

**Comment by 40823136** [comment]
https://40823136.github.io/cp2019/content/index.html

**Comment by 40823137** [comment]
https://40823137.github.io/cp2019/content/index.html

**Comment by 40823119** [comment]
https://40823119.github.io/cp2019/content/index.html

**Comment by 40823138** [comment]
https://40823138.github.io/cp2019/content/index.html

**Comment by 40823135** [comment]
https://40823135.github.io/cp2019/content/index.html

**Comment by 40823149** [comment]
https://40823149.github.io/cp2019/content/index.html

**Comment by 40823132** [comment]
https://40823132.github.io/cp2019/content/%E8%BF%B4%E5%9C%88%E7%A8%8B%E5%BC%8F.html

**Comment by 40823120** [comment]
https://40823120.github.io/cp2019/content/USB.html

**Comment by 40823146** [comment]
https://40823146.github.io/cp2019/content/index.html

**Comment by 40823140** [comment]
https://40823140.github.io/cp2019/content/index.html

**Comment by 40823103** [comment]
https://40823103.github.io/cp2019/content/index.html

**Comment by 40823141** [comment]
https://40823141.github.io/cp2019/content/index.html

**Comment by 40823126** [comment]
https://40823126.github.io/cp2019/content/index.html

**Comment by 40823107** [comment]
https://40823107.github.io/cp2019/content/index.html

**Comment by 40823107** [comment]
https://40823107.github.io/cp2019/content/%E8%BF%B4%E5%9C%88.html

**Comment by 40823116** [comment]
https://40823116.github.io/cp2019/content/LOOP.html

**Comment by 40823150** [comment]
https://40823150.github.io/cp2019/content/Have%20a%20nice%20day.html

**Comment by 40623155** [comment]
https://40623155.github.io/cp2019/content/%E8%BF%B4%E5%9C%88.html

**Comment by 40623156** [comment]
https://40623156.github.io/cp2019/content/DartPad.html

**Comment by 40623153** [comment]
https://40623153.github.io/cp2019/content/Dart.html

**Comment by 40823105** [comment]
https://40823105.github.io/cp2019/content/index.html

**Comment by 40823107** [comment]
https://40823107.github.io/cp2019/content/W6.html

**Comment by 40823101** [comment]
https://40823101.github.io/cp2019/content/index.html

**Comment by 40823114** [comment]
https://40823114.github.io/cp2019/content/index.html

**Comment by 40823143** [comment]
https://40823143.github.io/cp2019/content/index.html
