### ISSUE TITLE
1b W6 Dart for 迴圈程式原始碼與連結放入網頁回報

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/cp2019#9]
請參考 https://www.youtube.com/watch?v=PiJkXzTxHJc 中有關 main 主函式與 for 迴圈使用說明, 將第一個 for 迴圈應用程式原始碼引入個人頁面連結與 embed-dart.html 連結, 在下列回應中回報.

例如:

[引用 Dart 倉儲程式範例](https://mde.tw/cp2019/content/Dart2%20%E5%9F%BA%E6%9C%AC%E8%AA%9E%E6%B3%95)

請提供個人網頁中 w6 的頁面網路連結

**Comment by s40523124** [comment]
40523124
[引用 Dart 倉儲程式範例](https://s40523124.github.io/cp2019/content/w6.html)

**Comment by s40523113** [comment]
40523113
[程式碼](https://github.com/s40523113/cp2019/blob/master/downloads/dart_ex/for/main.dart)
[引用 Dart 倉儲程式範例](https://s40523113.github.io/cp2019/content/index.html)

**Comment by 40823217** [comment]
40823217
[引用Dart倉儲城市範例](https://40823217.github.io/cp2019/content/Dart.html)
[程式碼](https://github.com/40823217/cp2019/blob/master/downloads/for/main.dart)

**Comment by 40823235** [comment]
40823235
[引用Dart倉儲城市範例](https://40823235.github.io/cp2019/content/index.html)
[程式碼](https://github.com/40823235/cp2019/blob/master/downloads/Dart_ex/for/main.dart)

**Comment by s40523111** [comment]
40523111
[引用Dart倉儲城市範例](https://s40523111.github.io/cp2019/content/index.html)
[程式碼](https://github.com/s40523111/cp2019/blob/master/downloads/dart_ex/for/main.dart)

**Comment by 40823242** [comment]
40823242
[引用倉儲城市範例](https://localhost:8444/content/index.html)
[程式碼](https://github.com/40823242/cp2019/blob/master/downloads/dart_ex/for/main.dart)

**Comment by 40823234** [comment]
4082323
[引用Dart倉儲城市範例](https://40823234.github.io/cp2019/content/Dart.html)
[程式碼](https://github.com/40823234/cp2019/blob/master/downloads/for/main_dart)

**Comment by s40523108** [comment]
40523108
[引用倉儲城市範例](https://s40523108.github.io/cp2019/content/index.html)
[程式碼](https://github.com/s40523108/cp2019/blob/master/downloads/dart_ex/for/main.dart)

**Comment by 40823213** [comment]
40823213
[引用倉儲程式範例](https://localhost:8444/content/index.html)
[程式碼](https://github.com/40823213/cp2019/blob/master/downloads/dart_ex/for/main.dart)

**Comment by 40823245** [comment]
40823245
引用倉儲程式範例(https://localhost:8444/content/index.html)`
程式碼(https://github.com/40823245/cp2019/blob/master/downloads/dart_ex/for/main.dart)

**Comment by 40823224** [comment]
40823224
[引用倉儲程式範例](https://40823224.github.io/cp2019/content/index.html)
[程式碼](https://github.com/40823224/cp2019/blob/master/downloads/dart_ex/for/main.dart)

**Comment by s40523242** [comment]
40523242
[引用倉儲程式範例](https://s40523242.github.io/cp2019/content/W6.html)
[程式碼](https://github.com/s40523242/cp2019/blob/master/downloads/for/main.dart)

**Comment by 40823251** [comment]
40823251
引用倉儲程序[](https://40823251.github.io/cp2019/content/Dart2%E5%9F%BA%E6%9C%AC%E8%AA%9E%E6%B3%95.html)
程序碼[](https://gist.github.com/40823251/b2ab311ac1fa0cf1052755d3438a2d70)

**Comment by 40823212** [comment]
40823212
[引用倉儲程序](https://127.0.0.1:8444/content/index.html)
[程序碼](https://gist.github.com/40823212/dec6e25c2cb9262cafde8fe594cea4c5)

**Comment by 40823246** [comment]
40823246
[引用倉儲程序](https://40823246.github.io/cp2019/content/飛鏢.html)
[程序碼](https://github.com/40823246/cp2019/)

**Comment by 40823208** [comment]
40823208
[引用倉儲程序](https://40823208.github.io/cp2019/content/index.html)
[程序碼](https://github.com/40823208/cp2019/)

**Comment by 40823209** [comment]
40823209
[引用倉儲程序](https://40823209.github.io/cp2019/content/Tasks.html)
[程序碼](https://gist.github.com/40823209/557410407823a0804068d65d72fcd20a)

**Comment by 40823221** [comment]
40823221
[[引用倉儲程序]](https://40823221.github.io/cp2019/content/index.html)
[程序碼](https://gist.github.com/40823221/63e766a3effc5de8f5a58043e4c2ff33)

**Comment by 40823248** [comment]
40823248
[引用倉儲程序](https://40823248.github.io/cp2019/content/index.html)
[程序碼](https://gist.github.com/40823248/d3a58d3b770a70a58d9bbba3b023ab00)

**Comment by s40523241** [comment]
40523241
[引用倉儲程序](https://s40523241.github.io/cp2019/content/Dart.html)
[程序碼](https://github.com/s40523241/cp2019/blob/master/downloads/for/main.dart)

**Comment by 40823250** [comment]
40823250
[引用倉儲程序](https://40823250.github.io/cp2019/content/USB2.html)
[程序碼](https://gist.github.com/40823250/3cbfd0eab8e5bcef25e39f95ee544b07)

**Comment by 40823218** [comment]
40823218
引用倉儲程序
程序碼

**Comment by 40823218** [comment]
40823218
[引用倉儲程序](https://40823218.github.io/cp2019/content/dartpad.html)
[程序碼](https://gist.github.com/40823218/b41cb4114c0b5815f108758b4f25fa02)

**Comment by 40823222** [comment]
40823218
[引用倉儲程序](https://40823222.github.io/cp2019/content/index.html)
[程序碼](https://gist.github.com/40823222/bf6ff7404f8b6ec2ffd6e8ffaacdff68)

**Comment by 40823247** [comment]
40823247
[引用倉儲程序](https://40823247.github.io/cp2019/content/USB2.html)
[程序碼](https://gist.github.com/40823247/67f0af9fbfe9e2e64fa12d9d0ea9fc5b)

**Comment by 40823226** [comment]
40823218
[引用倉儲程序](https://40823226.github.io/cp2019/content/index.html)
[程序碼](https://gist.github.com/40823226/b74b6606258a024ee80fe6c099672d2a)

**Comment by 40823228** [comment]
40823228
[引用倉儲程序](https://40823228.github.io/cp2019/content/index.html)
[程序碼](https://gist.github.com/40823228/7b537e01e70c2ca5e20c778bb94b811c)

**Comment by 40823207** [comment]
40823207
[引用倉儲程序](https://40823207.github.io/cp2019/content/index.html)
[程序碼](https://gist.github.com/40823207/d98292193abc6d90a3118d7e41c70a86)

**Comment by 40823244** [comment]
40823244
[倉儲程序引用](https://40823244.github.io/cp2019/content/index.html)
[程序碼](https://gist.github.com/40823244/a0a73943bccb749341ca6a21921e5a82)

**Comment by 40823223** [comment]
40823223
[倉儲程序引用](https://40823223.github.io/cp2019/content/index.html)
[程序碼](https://gist.github.com/40823223/9fec2391f973ad5f6f3c574086cd3192)

**Comment by 40823239** [comment]
40823239
[倉儲程序引用](https://github.com/40823239/cp2019/)
[程序碼](https://localhost:8444/content/index.html)

**Comment by 40823233** [comment]
40823233
[倉儲程序引用](url)https://40823233.github.io/cp2019/content/index.html
[程序碼1](url)https://github.com/40823233/cp2019/blob/master/dart_ex/hello.dart
[程序碼2](url)https://github.com/40823233/cp2019/blob/master/dart_ex/for%20loop.dart

**Comment by 40823233** [comment]
40823233
[倉儲程序引用](https://40823233.github.io/cp2019/content/index.html)
[程序碼1](https://github.com/40823233/cp2019/blob/master/dart_ex/hello.dart)
[程序碼2](https://github.com/40823233/cp2019/blob/master/dart_ex/for%20loop.dart)

**Comment by 40823237** [comment]
40823237
[倉儲程式引用](https://40823237.github.io/cp2019/content/index.html)
[程式碼](https://github.com/40823237/cp2019/blob/master/downloads/dart_ex/for/main.dart)

**Comment by 40823211** [comment]
40823211
[倉儲程式引用](https://localhost:8444/content/index.htmlrl)
[程式碼](https://github.com/40823211/cp2019/tree/master/downloads/dart_ex/for)

**Comment by s40523207** [comment]
40523207
[引用 Dart 倉儲程式範例](https://s40523207.github.io/cp2019/content/index.html)
[程式碼](https://github.com/s40523207/cp2019/blob/master/downloads/dart_ex/for/main.dart)

**Comment by 40823210** [comment]
[引用 Dart 倉儲程式範例](https://40823210.github.io/cp2019/content/For%E8%BF%B4%E5%9C%88.html)
[程式碼](https://github.com/40823210/cp2019/blob/master/downloads/dart_ex/for/main.dart)

**Comment by 40823205** [comment]
[引用 Dart 倉儲程式](https://40823205.github.io/cp2019/content/index.html)
[程式碼](https://github.com/40823205/cp2019/blob/master/downloads/dart_ex/for/main.dart)

**Comment by 40823201** [comment]
[引用Dart倉儲程式](https://40823201.github.io/cp2019/content/index.html)
[程式碼](https://github.com/40823201/cp2019/blob/master/downloads/dart_ex/for/main.dart)

**Comment by 40823225** [comment]
[引用Dart倉儲程式](https://40823225.github.io/cp2019/content/index.html)
[程式碼](https://gist.github.com/40823225/d546cffc84c95439c18ff2030a518292)

**Comment by 40823202** [comment]
[引用Dart倉儲](https://40823202.github.io/cp2019/content/計算機程式.html)
[程式碼](https://gist.github.com/40823202/a9dee6c9f862cf5db40b67c7226e8b26)

**Comment by 40823202** [comment]
> [引用Dart倉儲程式](https://40823225.github.io/cp2019/content/index.html)
> [程式碼](https://gist.github.com/40823202/a9dee6c9f862cf5db40b67c7226e8b26)

**Comment by 40823203** [comment]
[引用Dart倉儲程式](https://40823203.github.io/cp2019/content/index.html)
[程式碼](https://gist.github.com/40823203/b3a63061d37858778e510273b2eec602)

**Comment by 40823230** [comment]
[引用 Dart 倉儲程式](https://40823230.github.io/cp2019/content/USB2.html)
[程式碼](https://github.com/40823230/cp2019/blob/master/downloads/dart_ex/for/main.dart)

**Comment by 40623155** [comment]
[引用 Dart 倉儲程式](https://40623155.github.io/cp2019/content/%E8%BF%B4%E5%9C%88.html)
[程式碼](https://github.com/40623155/cp2019/blob/master/downloads/dart_ex/for/main.dart)

**Comment by 40623156** [comment]
[引用 Dart 倉儲程式](https://40623156.github.io/cp2019/content/DartPad.html)

**Comment by 40623153** [comment]
[引用 Dart 倉儲程式](https://40623153.github.io/cp2019/content/Dart.html)
[程式碼](https://gist.github.com/40623153/ae38a6898f4dd731f3ddc272835443e7)
